# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e7b813567176eef1c9dc2dda96890a1ded90d6675cb7408dd9f9f48b8f283e1b54e1d18610cdfa7a06c1416838fbead27c9a7fd4b885110a5f6a58363d94e75b

test:
  secret_key_base: a4dba353b5cd968c7388eeb0f794d0cc69f5badbec62c7401c9d9c00409e586e417e26228e69fba0d8916f5ad82536d738fa161ac53ffda53bed26ba6da3cce9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
